"""Canonical doc-search database surface."""

from repowise.docs.db_jobs import (
    claim_job,
    complete_job,
    enqueue_job,
    fail_job,
    get_job,
    heartbeat_job,
    list_jobs,
    reclaim_stale_jobs,
)
from repowise.docs.db_libraries import (
    count_libraries,
    delete_library,
    delete_library_file,
    delete_library_files,
    get_library,
    get_library_file,
    get_library_files,
    list_libraries,
    mark_graph_sync_pending,
    migrate_library_alias,
    update_library_status,
    upsert_library,
    upsert_library_file,
)
from repowise.docs.db_runtime import close_pool, get_connection, get_pool, init_pool
from repowise.docs.db_snapshots import (
    SnapshotFileInput,
    compute_manifest_hash,
    get_snapshot_file,
    get_snapshot_state,
    list_snapshot_files,
    replace_snapshot,
)

__all__ = [
    "SnapshotFileInput",
    "claim_job",
    "close_pool",
    "complete_job",
    "compute_manifest_hash",
    "count_libraries",
    "delete_library",
    "delete_library_file",
    "delete_library_files",
    "enqueue_job",
    "fail_job",
    "get_connection",
    "get_job",
    "get_library",
    "get_library_file",
    "get_library_files",
    "get_pool",
    "get_snapshot_file",
    "get_snapshot_state",
    "heartbeat_job",
    "init_pool",
    "list_jobs",
    "list_libraries",
    "list_snapshot_files",
    "mark_graph_sync_pending",
    "migrate_library_alias",
    "reclaim_stale_jobs",
    "replace_snapshot",
    "update_library_status",
    "upsert_library",
    "upsert_library_file",
]
