"""Chunk post-processing optimizers for improving index quality."""

from __future__ import annotations

import re

from repowise.docs.chunking.extractors.text_split import estimate_tokens
from repowise.docs.chunking.models import DocChunk

PART_ANCHOR_RE = re.compile(r"^(?P<base>.*)-part-(?P<n>\d+)$")
CODE_PART_ANCHOR_RE = re.compile(r"^(?P<base>.*)-code-part-(?P<n>\d+)$")


def _base_anchor(anchor: str) -> str:
    for pattern in (CODE_PART_ANCHOR_RE, PART_ANCHOR_RE):
        match = pattern.match(anchor)
        if match:
            return match.group("base")
    return anchor


def _is_split_tail_anchor(anchor: str) -> bool:
    for pattern in (CODE_PART_ANCHOR_RE, PART_ANCHOR_RE):
        match = pattern.match(anchor)
        if not match:
            continue
        try:
            part_num = int(match.group("n"))
        except ValueError:
            return False
        return part_num >= 2
    return False


def _resolve_id(value: str, mapping: dict[str, str]) -> str:
    seen: set[str] = set()
    current = value
    while current in mapping and current not in seen:
        seen.add(current)
        current = mapping[current]
    return current


def greedy_merge_split_tails(
    chunks: list[DocChunk],
    *,
    max_tokens: int,
    min_tokens: int,
) -> list[DocChunk]:
    """
    Merge tiny split-tail chunks back into the preceding sibling.

    Merges chunks that:
    - are split tails (-part-N or -code-part-N, N>=2)
    - have the same chunk_type and base anchor as the preceding chunk
    - have the same parent_chunk_id as the preceding chunk
    - are smaller than min_tokens
    - still fit within max_tokens after merge

    If a merge occurs, the destination chunk's ID is regenerated by calling
    __post_init__. Any child chunks that referenced the old ID via
    parent_chunk_id are updated to the new ID.
    """
    if not chunks:
        return []

    optimized: list[DocChunk] = []
    id_mapping: dict[str, str] = {}

    for chunk in chunks:
        if not optimized:
            optimized.append(chunk)
            continue

        prev = optimized[-1]

        # Check if this is a split tail that should be merged
        is_split_tail = (
            _is_split_tail_anchor(chunk.section_anchor)
            and chunk.chunk_type == prev.chunk_type
            and _base_anchor(chunk.section_anchor) == _base_anchor(prev.section_anchor)
            and chunk.parent_chunk_id == prev.parent_chunk_id
        )

        if is_split_tail:
            separator = "\n" if CODE_PART_ANCHOR_RE.match(chunk.section_anchor) else "\n\n"
            merged_content = f"{prev.content}{separator}{chunk.content}"
            merged_tokens = estimate_tokens(merged_content)

            if estimate_tokens(chunk.content) < min_tokens and merged_tokens <= max_tokens:
                old_id = prev.id
                prev.content = merged_content
                prev.metadata |= {k: v for k, v in chunk.metadata.items() if k not in prev.metadata}
                prev.__post_init__()
                id_mapping[old_id] = prev.id
                continue

        optimized.append(chunk)

    # Update parent references for any chunks whose parents were merged/re-id'd
    if id_mapping:
        for chunk in optimized:
            if chunk.parent_chunk_id:
                chunk.parent_chunk_id = _resolve_id(chunk.parent_chunk_id, id_mapping)

    return optimized
